site_name: Платформа поиска людей в команду — ЛР1
theme:
  name: material
  language: ru
nav:
  - Главная: index.md
  - Модели данных: models.md
  - Практики:
      - Практика 1: practices/practice1.md
      - Практика 2: practices/practice2.md
      - Практика 3: practices/practice3.md
  - API:
      - Пользователи: api/users.md
      - Навыки: api/skills.md
      - Проекты: api/projects.md
      - Команды: api/teams.md
      - Авторизация: api/auth.md
