"""full data model

Revision ID: dcc627f340f5
Revises: d4b554615e44
Create Date: 2026-03-24 23:25:50.434201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcc627f340f5'
down_revision: Union[str, Sequence[str], None] = 'd4b554615e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("ALTER TYPE roletype ADD VALUE IF NOT EXISTS 'tester'")
    )
    op.execute(
        sa.text("ALTER TYPE roletype ADD VALUE IF NOT EXISTS 'devops'")
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teammember',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.add_column(
        'project',
        sa.Column(
            'status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='open',
        ),
    )
    op.execute(
        sa.text(
            "UPDATE project SET required_skills = '' WHERE required_skills IS NULL"
        )
    )
    op.alter_column('project', 'required_skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column(
        'user',
        sa.Column(
            'hashed_password',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='',
        ),
    )
    op.alter_column('user', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('user_project_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_project_id_fkey'), 'user', 'project', ['project_id'], ['id'])
    op.alter_column('user', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'hashed_password')
    op.alter_column('project', 'required_skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('project', 'status')
    op.drop_table('teammember')
    op.drop_table('team')
    # ### end Alembic commands ###
